### PR TITLE
Reorganise MapLibre Qt bindings into multiple libraries

### PR DESCRIPTION
**Pull request by ntadej**
Reorganise Qt bindings into multiple libraries:
 - `QMapLibre`: core library
 - `QMapLibreWidgets`: widgets (currently OpenGL widget)
 - `QMapLibreLocation`: Qt Location bindings (with 2 plugins)

For now this builds on Linux and macOS. Will follow-up on other platforms later. Note that for Qt5 only desktop support is planned at this point (mainly for Windows).

API for newly added stuff is still rough, but I want a setup that builds nicely and passes tests!

Note that this PR is large, but I split it into more logical commits. Will try to merge without squashing.

Tagging also @kebekus @kamilhajdukiewicz @petricf @emericg

### CODE REVIEW

**Comment by emericg** [comment]
Trying to build your branch on ArchLinux, Qt 6.5.3 and Qt 6.6.0, it fails while building maplibre-native. Error log is huge, let me know if you need everything.

FAILED: src/core/MapLibreCore/CMakeFiles/mbgl-core.dir/src/mbgl/gfx/shader_registry.cpp.o 
/maplibre-native-ntadej/vendor/maplibre-native/src/mbgl/gfx/shader_registry.cpp: Dans le constructeur « mbgl::gfx::ShaderRegistry::ShaderRegistry() »:
/maplibre-native-ntadej/vendor/maplibre-native/src/mbgl/gfx/shader_registry.cpp:7:32: erreur: utilisation de la fonction supprimée « std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map() [avec _Key = std::__cxx11::basic_string<char>; _Tp = std::shared_ptr<mbgl::gfx::Shader>; _Hash = std::hash<std::__cxx11::basic_string<char> >; _Pred = std::equal_to<std::__cxx11::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::__cxx11::basic_string<char>, std::shared_ptr<mbgl::gfx::Shader> > >] »
7 | ShaderRegistry::ShaderRegistry() {}
/usr/include/c++/13.2.1/bits/unordered_map.h:148:7: note: « std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map() [avec _Key = std::__cxx11::basic_string<char>; _Tp = std::shared_ptr<mbgl::gfx::Shader>; _Hash = std::hash<std::__cxx11::basic_string<char> >; _Pred = std::equal_to<std::__cxx11::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::__cxx11::basic_string<char>, std::shared_ptr<mbgl::gfx::Shader> > >] » est implicitement supprimé car la définition par défaut serait mal formée:
  148 |       unordered_map() = default;
      |       ^~~~~~~~~~~~~
/maplibre-native-ntadej/vendor/maplibre-native/src/mbgl/gfx/shader_registry.cpp:48:21:   requis depuis ici
/usr/include/c++/13.2.1/type_traits:1048:52: erreur: l'assertion statique a échoué: template argument must be a complete class or an unbounded array
 1048 |       static_assert(std::__is_complete_or_unbounded(__type_identity<_Tp>{}),
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~

**Comment by ntadej** [comment]
I guess the compiler is too new. Will look into it.

**Comment by louwers** [comment]
Looks unrelated to Qt to be honest.

**Comment by birkskyum** [comment]
@emericg , Qt 6.6? afaik it isn't released yet - are you using the RC?

**Comment by emericg** [comment]
> @emericg , Qt 6.6? afaik it isn't released yet - are you using the RC?

Yes indeed, but as @louwers said I don't think it's related to Qt either.

I'm trying every beta now, and I have a lot of versions installed in parallel, because for every release of Qt6 (including point release, but these don't have beta unfortunately) it has been way (waay) too easy to find huge and breaking bugs in the most basic workflows. The sooner these can be reported the better...

**Comment by ntadej** [comment]
@emericg, you can try again, the code should now build with GCC 13.

**Comment by emericg** [comment]
I've got a failure when building with Qt 6.6 (out now ^^) but that's easy to "fix" and looking at the comments you are aware of what's going on there. And it builds alright with Qt 6.5.
```
/maplibre-native-ntadej/src/location/stylechange.cpp:60:39: erreur: « calculatePeripheralPoints » n'est pas un membre de « QDeclarativeCircleMapItemPrivate »
```

But I've also got linking failure, with both Qt versions, seems to be because of ICU.
```
/usr/bin/ld : src/core/libQMapLibre.so.3.0.0 : référence indéfinie vers « ubidi_close_73 »
/usr/bin/ld : src/core/libQMapLibre.so.3.0.0 : référence indéfinie vers « ubidi_open_73 »
```

My system has ICU 73.2 and the build system try to use it, but looks like there is a copy of ICU 71 in the maplibre vendor directory, so I've enabled it and it seems to finish the build.
I found [this page](https://github.com/maplibre/maplibre-native/blob/main/platform/qt/README.md) after this message, now I feel like I really should read the manuals :/ But still both options (icu and the install prefix) should probably be on this plugin README.



And now it loads! With both Qt 6.5 and 6.6. At first, it was... orange. The project I tried initially was loading zoomed and locked on my city, so I thought it wasn't actually working. But the default map is indeed orange here.

I've tried this from an open issue, it's not doing anything. The supported map type is stuck on `QGeoMapType(1, maplibre://maps/style, Basic, false, false, , )`
```
PluginParameter { name: "maplibre.mapping.additional_style_urls"; value: "https://tiles.versatiles.org/styles/colorful.json" }
PluginParameter { name: "maplibre.api_base_url"; value: "https://tiles.versatiles.org:8080/api" }
```
I've tried other things, but long story short, I'm not sure if it is a bug or if I have absolutely no idea on how to set another map style or provider. It's my first time using maplibre, but still there should be an example or plugin parameters documentation on how to change the style?

**Comment by ntadej** [comment]
Yes, I need to add all the compile options here.

I also plan to provide some documentation, although I have problems with QDoc as it does not really look like being suited for external Qt projects (or maybe I'm doing something wrong there).

As for changing the style, only "maplibre.mapping.additional_style_urls" is needed, but then you also need to choose the style in QML Map object (something like `activeMapType: supportedMapTypes[someIndex]`).

**Comment by petricf** [comment]
Built on Debian 12 (linux amd64).

Compiles well (with some warnings). At the end i got
 `     /usr/bin/ld: warning: libicuuc.so.56, needed by /home/petric/Qt/6.5.2/gcc_64/lib/libQt6Core.so.6.5.2, may conflict with libicuuc.so.72`

Reason: Debian delivers v72 whereas Qt online installer provides v72. I assume i can ignore this warning if i use LD_LIBRARY_PATH to override the location.

Linkage option "-Wl,rpath,..." may help (untested) - Linux platform, others unknown. 

Functional test is ongoing.

Environment:
`    OS Debian Linux 12.2 (Bookworm)`
`    gcc version 12.2.0 (Debian 12.2.0-14)`
`    GNU ld (GNU Binutils for Debian) 2.40`
`    QMake version 3.1`
`    ninja 1.11.1`
`    Qt 6.5.2 (by Qt online installer placed to directory /home/petric/Qt/6.5.2/...)`

Debian stable does not deliver Qt6Location. But qt6positioning(-dev)/libqt6positioning is part of stable debian. Is that enough to compile/use this plugin ?

If yes i will try to use stock debian Qt6 to build it. Advantage: the *.deb can be installed w/o additional Qt libs outside debian. It perhaps solves the icu problem also.

**Comment by emericg** [comment]
> OK, can you maybe open an issue for the map switch? I'll work on it next after this is merged also adding some examples.

No problem, I just opened an issue. And thank you for working on this plugin, this is probably the only viable future for QtLocation...

A while ago I was using the _mapbox_ plugin for Qt5, with great results. But even in "the end" of Qt 5, support was starting to show some serious signs of weaknesses.
I only discovered MapLibre last month, after realizing the _osm_ plugin (now the only plugin) for Qt Location 6 wasn't even able to correctly display a simple (and poor looking) map anymore.

Also it would be helpful to quickly recap what this plugin can do in the README, in relation to the larger MapLibre ecosystem. Does the plugin only support tiles? What about vector maps? The renderer is OpenGL or software? Or can do both? Will the metal implementation be a part of the plugin eventually? Will the terrain and globe view ever be supported?

**Comment by emericg** [comment]
> Debian stable does not deliver Qt6Location. But qt6positioning(-dev)/libqt6positioning is part of stable debian. Is that enough to compile/use this plugin ?

@petricf  

**QtPositioning** is only to get your position from various sources like GPS on mobile or wifi on desktop.  
**QtLocation** is the mapping infrastructure. You can use QtPositioning to draw an icon on the map to visualize your position, but the two modules are independent.

**Comment by petricf** [comment]
Thanks for clarifying.

Qt Maintenance Tool starts providing QtLocation from 6.5 onwards as technical preview. I assume Debian as result does not deliver it because here the Qt version in use is 6.4.x.

Standard Qt on Debian is 5.15.8. Here they provide a *.debs for QtLocation.

**Comment by ntadej** [comment]
> Thanks for clarifying.
> 
> Qt Maintenance Tool starts providing QtLocation from 6.5 onwards as technical preview. I assume Debian as result does not deliver it because here the Qt version in use is 6.4.x.
> 
> Standard Qt on Debian is 5.15.8. Here they provide a *.debs for QtLocation.

For 6.4 I provide a patched version of QtLocation that you could use (https://github.com/ntadej/qtlocation), but I'm not sure we should support that moving forward, depending on the need of the community.

**Comment by petricf** [comment]
As i have seen that ntadej made Qt6Location releases under https://github.com/ntadej/qtlocation.

I try to repackage the release (6.4.2) as binary *.deb. Hopefully this would enable to release a maplibre-qt package for stable Debian. As long i get it compiling - see issue #33.

**Review by birkskyum — APPROVED** [review]

**Pull request merged**
