### PR TITLE
Update CMake packaging and test with examples

### PR DESCRIPTION
**Pull request by ntadej**
Improve how CMake package is exported. Now one does
```
find_package(QMapLibre COMPONENTS Core REQUIRED)
```
or
```
find_package(QMapLibre COMPONENTS Widgets REQUIRED)
```

Also update and cleanup the examples and test the installation using them.

@birkskyum, you can start using the widgets example for WASM. Separately I'll prepare a branch for the unstable WASM experiments.

### CODE REVIEW

**Review by birkskyum — APPROVED** [review]

**Comment by birkskyum** [comment]
> @birkskyum, you can start using the widgets example for WASM. 

doesn't that require this experimental singleton as well?

**Comment by ntadej** [comment]
Yes, but while you're waiting, you may as well already try to build with this setup. Just changing the branch later will be very fast (especially if you use ccache).

**Comment by birkskyum** [comment]
So, I'd be cloning `maplibre-native-qt`, and then from a sibling folder run something like this? How do I specify which executable to run?

```
qt-cmake ../maplibre-native-qt \   
-G Ninja \
-DCMAKE_BUILD_TYPE="RelWithDebInfo" \
-DMLN_WITH_QT=ON \
-DMLN_QT_STATIC=ON \
-DMLN_QT_WITH_INTERNAL_SQLITE=ON
```

**Comment by ntadej** [comment]
See the README 😉

First you build MapLibre with
```
mkdir build && cd build
cmake ../maplibre-native-qt -GNinja \
  -DCMAKE_BUILD_TYPE="RelWithDebInfo" \
  -DCMAKE_C_COMPILER_LAUNCHER="ccache" \
  -DCMAKE_CXX_COMPILER_LAUNCHER="ccache" \
  -DCMAKE_INSTALL_PREFIX="../install" \
  -DMLN_QT_WITH_INTERNAL_SQLITE=ON
ninja
ninja install
```

Then you build the widgets example
```
mkdir build-example && cd build-example
qt-cmake ../maplibre-native-qt/examples/widgets -GNinja \
  -DCMAKE_C_COMPILER_LAUNCHER="ccache" \
  -DCMAKE_CXX_COMPILER_LAUNCHER="ccache" \
  -DCMAKE_PREFIX_PATH="<absolute-path-to-install>"
ninja
```

**Pull request merged**
