### PR TITLE
Run iOS CI on self-hosted runners

### PR DESCRIPTION
**Pull request by ntadej**
FYI @birkskyum

Note that I will merge this after I release the bugfix release.

### CODE REVIEW

**Comment by ntadej** [comment]
OK, it seems we have to install Python.

**Comment by birkskyum** [comment]
Awesome, If the runners don't start it's likely because of some reconfiguration work.

**Comment by birkskyum** [comment]
https://github.com/maplibre/maplibre-gl-native/issues/485

**Comment by birkskyum** [comment]
if you list any software you expect will be needed in this issue i linked, I'll make sure they support it

**Comment by wipfli** [comment]
Ah so the runners from maplibre/maplibre-gl-native are usable across the entire github org?

**Comment by ntadej** [comment]
@birkskyum should we retry these again? I saw you closed the ticket.

**Comment by birkskyum** [comment]
I did retry them actually - it didn't work, but I think it's because of all this setup-python. It shouldn't be necessary at all.

**Comment by ntadej** [comment]
It seems that upstream support is being worked on. Maybe we just need to wait a bit longer.

**Comment by birkskyum** [comment]
I think the macos runners recently have been reconfigured in GitHub to be maplibre-gl-native only @louwers

**Comment by ntadej** [comment]
OK, I can close this.

I can also investigate using https://cirrus-ci.org which seems to have more generous free resources.

**Comment by louwers** [comment]
Let me know if you need a macOS runner still.

**Comment by ntadej** [comment]
I think for now we are fine. The MR frequency is not that high and `ccache` seems to work reasonably well. This may change when we re-enable iOS, but let's see.

**Review by louwers — CHANGES_REQUESTED** [review]
I think this can be closed.

**Pull request closed without merging**
